services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fmcg_inventory
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DATABASE_USER:-postgres}
      DB_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DB_NAME: ${DATABASE_NAME:-fmcg_dev}
    entrypoint: ["sh", "-c", "npm run migrate && npm run start"]
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: fmcg-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-fmcg_dev}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  app_network:
    driver: bridge
